<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LMU_Excel_Sync</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>LMU_GS.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="LMU_GS.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="RaceLogger.App\**" />
    <EmbeddedResource Remove="RaceLogger.App\**" />
    <None Remove="RaceLogger.App\**" />
  </ItemGroup>

</Project>
